#ifndef SIGNALGENERATOR_CONFIG_H
#define SIGNALGENERATOR_CONFIG_H

const uint16_t OUTPUT_PIN = 16;
const uint16_t ON_OFF_SWITCH_PIN = 4;
const uint16_t SQUARE_WAVE_BUTTON_PIN = 12;
const uint16_t TRIANGLE_WAVE_BUTTON_PIN = 13;
const uint16_t SAWTOOTH_WAVE_BUTTON_PIN = 14;
const uint16_t SINE_WAVE_BUTTON_PIN = 15;
const uint16_t POTENTIOMETER_FREQUENCY_INPUT_PIN = 27;
const uint16_t POTENTIOMETER_FREQUENCY_INPUT_ADC = 1;

const uint16_t SAMPLES_PER_PERIOD = 255;
const uint16_t PWM_OUTPUT_RESOLUTION = 65535;

#endif //SIGNALGENERATOR_CONFIG_H
